Repository LibreHealthIO/lh-ehr, pull requests merged in 2018-07, with the labels that each got.

#1203 Scroll time and provider in Calendar views
  modules/calendar/index.php
Labels: Feature: Calendar, Review Requested!, Tested

#1196 Statement download name change
  sites/default/statement.inc.php
Labels: Consistency/Code Formatting

#1216 changed the +'s to .'s
  library/globals.inc.php
Labels: bug

#1176 GSoC 2018 : Calendar Improvements-Audit feature for Appointments.
  interface/main/finder/select_patient.php
  interface/patient_file/history/track_appointments.php
  interface/patient_file/history/track_appointments_ajax.php
  interface/patient_file/summary/appointment_log.php
  interface/patient_file/summary/demographics.php
  library/globals.inc.php
  sites/default/menu_data.json
Labels: Feature: NEW, Feature: Calendar, enhancement
