Repository LibreHealthIO/lh-ehr, pull requests merged in 2018-06, with the labels that each got.

#1163 Added the ability to display the status colors
  library/globals.inc.php
  modules/calendar/includes/get_provider_events.php
Labels: Feature: Calendar

#1142 Clean up the code for the next set of changes
  modules/calendar/add_edit_event.php
  sql/2_0_0-to-2_0_1_upgrade.sql
  sql/database.sql
  version.php
Labels: Review Requested!, Tested

#1103 enhanced pre-authorization form
  interface/forms/enhanced_prior_auth/info.txt
  interface/forms/enhanced_prior_auth/new.php
  interface/forms/enhanced_prior_auth/report.php
  interface/forms/enhanced_prior_auth/save.php
  interface/forms/enhanced_prior_auth/table.sql
  interface/forms/enhanced_prior_auth/view.php
  interface/forms/prior_auth_enhanced/C_FormPriorAuth.class.php
  interface/forms/prior_auth_enhanced/FormPriorAuth.class.php
  interface/forms/prior_auth_enhanced/display.php
  interface/forms/prior_auth_enhanced/new.php
  interface/forms/prior_auth_enhanced/report.php
  interface/forms/prior_auth_enhanced/save.php
  interface/forms/prior_auth_enhanced/table.sql
  interface/forms/prior_auth_enhanced/templates/prior_auth/general_new.php
  interface/forms/prior_auth_enhanced/view.php
  library/appointments.inc.php
  library/formsoptions.inc.php
Labels: Feature: NEW, Feature: BILLING, Review Requested!, Tested

#1166 Adding event description after hyperlink
  modules/calendar/includes/get_provider_events.php
  modules/calendar/index.php
Labels: Review Requested!, Tested

#1164 This fixed some recurring errors.
  modules/calendar/add_edit_event.php
Labels: Review Requested!, Tested, bug

#1168 Adding a means to check if a form is active
  library/formsoptions.inc.php
Labels: Feature: Clinical Forms

#1170 Added back the ability to create a patient
  modules/calendar/add_edit_event.php
  modules/calendar/find_patient_popup.php
Labels: Feature: Calendar

#1156 Fix for #1145: Refactor facility list in calendar
  modules/calendar/index.php
Labels: Feature: Calendar, UI: Layout, Usability

#1115 Fixed some buttons
  interface/orders/pending_orders.php
  interface/orders/procedure_stats.php
  interface/reports/cdr_log.php
  interface/themes/style_light.css
  interface/usergroup/facility_user.php
  modules/MIPS/clinical_measures.php
  modules/MIPS/measure_activate.php
  modules/MIPS/report_results.php
  modules/MIPS/reset_provider_to_unassigned.php
  modules/MIPS/truncate_reports.php
Labels: UI: Style/Menu/Label

#1161 GSoC 2018 : Calendar Improvements-Event based refresh
  interface/usergroup/facilities.php
  interface/usergroup/usergroup_admin.php
  library/calendar.inc
  modules/calendar/add_edit_event.php
Labels: Feature: NEW, Feature: Calendar, Review Requested!, Tested, User Request

#1174 Fix error in file
  library/gen_x12_837.inc.php
Labels: bug

#1150 Menu tabs user_data_template error
  interface/main/tabs/templates/user_data_template.php
Labels: Directory Structure, UI: Style/Menu/Label, bug

#1151 Favicon.ico 404 errors
  sql_patch.php
  sql_upgrade.php
Labels: Feature: SETUP, bug

#1137 Fix calendar schedule facilities
  interface/usergroup/user_admin.php
  modules/calendar/add_edit_event.php
Labels: Feature: Calendar, Feature: SECURITY/ACL, Tested, bug

#1132 MigDinny patient_report accordion
  interface/patient_file/report/patient_report.php
Labels: Feature: Patient Demographics, Feature: Reports, UI: Layout

#1173 Commented the unused code
  interface/forms/LBF/view.php
  interface/forms/track_anything/create.php
  interface/main/main_title.php
  interface/new/new.php
  library/globals.inc.php
  modules/calendar/add_edit_event.php
  modules/util_menu/menu.sql
  sql/1_0_1-to-2_0_0_upgrade.sql
Labels: Re-Factoring

#1179 Set Calendar time zone
  interface/globals.php
  interface/super/edit_globals.php
  library/globals.inc.php
Labels: Feature: Calendar, Feature: SETUP, GSoC2018, enhancement

#1134 Refactoring Facilities for iziModal
  interface/usergroup/facilities.php
  interface/usergroup/facilities_add.php
  interface/usergroup/facility_admin.php
Labels: Review Requested!, UI: Layout, UI: Administration, UI: Refactor
