Repository LibreHealthIO/lh-ehr, pull requests merged in 2018-03, with the labels that each got.

#1037 Added version number for portal
  interface/globals.php
  patient_portal/home.php
  patient_portal/patient/templates/_Footer.tpl.php
Labels: Feature: Patient Portal

#1044 color picker module added
  interface/globals.php
  interface/main/tabs/main.php
  interface/super/edit_globals.php
  interface/themes/style.php
  library/globals.inc.php
  library/headers.inc.php
Labels: UI: Style/Menu/Label, enhancement

#1043 Fullscreen program feature
  interface/main/main_screen.php
  interface/main/tabs/fullscreen.php
  interface/patient_tracker/patient_tracker.php
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
  interface/usergroup/usergroup_admin_add.php
  library/ajax/get_fullscreen_pages.php
  sql/1_0_1-to-2_0_0_upgrade.sql
  sql/database.sql
Labels: Feature: NEW

#1016 Fix #1011: Create an attached Document validation tool
  interface/usergroup/docs_validation.php
  sites/default/menu_data.json
Labels: Feature: NEW, UI: Administration

#1084 Fix for #242: Notify when globals saved
  interface/super/edit_globals.php
Labels: UI: Administration
