Repository LibreHealthIO/lh-ehr, pull requests merged in 2018-02, with the labels that each got.

#991 Add pre_billing_issues report
  sites/default/menu_data.json
Labels: Feature: Reports, UI: Style/Menu/Label

#997 Visibility of PRINT button according to selection of PAPER
  interface/forms/procedure_order/new.php
Labels: FEATURE: Printing/Export

#1027 text fields, menu layouts are not saved after validation PR
  interface/super/edit_globals.php
Labels: Feature: Sanity Checks

#1028 remove Refer menu item
  sites/default/menu_data.json
Labels: DEMOLITION, House Keeping, UI: Style/Menu/Label

#1005 Added back the images and fixed the CSS
  assets/css/jquery-gritter/jquery.gritter.css
  assets/images/gritter.png
  assets/images/ie-spacer.gif
Labels: bug

#1029 title tag added to the login page
  interface/login/login.php
Labels: UI: Style/Menu/Label
