Repository LibreHealthIO/lh-ehr, pull requests merged in 2018-05, with the labels that each got.

#1104 Profile picture feature for users
  interface/main/tabs/templates/user_data_template.php
  interface/usergroup/user_info.php
  interface/usergroup/usergroup_admin.php
  interface/usergroup/usergroup_admin_add.php
  sql/2_0_0-to-2_0_1_upgrade.sql
  sql/database.sql
Labels: Feature: NEW, Tested, UI: Layout

#1125 Installer to menu
  sites/default/menu_data.json
Labels: Feature: M.U. 3, Feature: NEW

#1129 Fix for cancellation reasons
  sql/2_0_0-to-2_0_1_upgrade.sql
  sql/database.sql
Labels: bug

#1133 Fix for the onset dated code
  library/gen_x12_837.inc.php
Labels: bug

#1130 /custom directory cleanup.
  custom/readme_search.txt
  custom/search.php
  interface/reports/chart_tracker.php
  modules/MIPS/boneyard/ajax_download.php
  modules/MIPS/boneyard/cqm.php
  modules/MIPS/boneyard/download_qrda.php
  modules/MIPS/boneyard/export_demographics.php
  modules/MIPS/boneyard/export_qrda_xml.php
  modules/MIPS/boneyard/export_xml.php
  modules/MIPS/boneyard/import_xml.php
  modules/MIPS/boneyard/qrda_category1.inc
  modules/MIPS/boneyard/qrda_category1_functions.php
  modules/MIPS/boneyard/qrda_download.php
  modules/MIPS/boneyard/qrda_functions.php
  sites/default/config.php
  sites/default/menu_data.json
  sites/default/readme_rx_printtofax.txt
  sites/default/rx_addendum.txt
Labels: DEMOLITION, House Keeping, Modularization

#952 interface\login & interface\logview library refactor
  interface/login/login.php
  interface/logview/erx_logview.php
  interface/logview/logview.php
Labels: GCI Task, Modularization, Re-Factoring

#1036 validation for files upload and multiple file uploads enabled
  interface/super/manage_site_files.php
Labels: enhancement

#1131 migdinny fee posting error fix
  interface/billing/sl_eob_search.php
Labels: Feature: Sanity Checks, Feature: BILLING

#1148 GSoC 2018 : Calendar Improvements-Hyperlink the patient name
  modules/calendar/index.php
Labels: Review Requested!, Tested

#1158 Add status delete alert in patient event panel
  modules/calendar/add_edit_event.php
Labels: Review Requested!, Tested

#1149 Calendar Cancellation Reasons sql fix
  sql/2_0_0-to-2_0_1_upgrade.sql
  sql/database.sql
Labels: Feature: Calendar, Feature: DATABASE, Feature: SETUP, Tested, bug
