Repository LibreHealthIO/lh-ehr, pull requests merged in 2018-10, with the labels that each got.

#1206 Change facility dynamic iziModal refresh
  interface/usergroup/facilities.php
Labels: GSoC2018, Tested, UI: Administration, Usability, bug

#1199 Event drag-resize-copy feature
  library/appointments.inc.php
  library/encounter_events.inc.php
  modules/calendar/drag_copy_event.php
  modules/calendar/fullcalendar-rightclick-1.9/LICENSE.txt
  modules/calendar/fullcalendar-rightclick-1.9/README.md
  modules/calendar/fullcalendar-rightclick-1.9/fullcalendar-rightclick.js
  modules/calendar/index.php
Labels: Feature: NEW, Feature: Calendar, Tested

#1266 Fix for the autocreate encounters
  library/encounter_events.inc.php
Labels: bug
