Repository LibreHealthIO/lh-ehr, pull requests merged in 2019-01, with the labels that each got.

#1349 Fix: Select Measure Style
  modules/MIPS/measure_activate.php
Labels: GCI Task, UI: Style/Menu/Label

#1364 feat: iziToast replaces browser alerts
  interface/new/new_comprehensive.php
Labels: GCI Task, UI: Refactor, UI: Style/Menu/Label

#1338 Fixes #1327 - 404 from Import , Export and XML Editor
  sites/default/menu_data.json
Labels: FEATURE: Printing/Export, GCI Task

#1376 Back Button Added to Ledger
  interface/reports/pat_ledger.php
Labels: enhancement

#1365 style: form administration tables
  interface/forms_admin/forms_admin.php
Labels: GCI Task, UI: Administration, UI: Refactor, UI: Style/Menu/Label

#1165 GSoC 2018 Project: PDF generator code for Patient Report section
  interface/patient_file/report/patient_report.php
  modules/pdf_generator/report/billing.php
  modules/pdf_generator/report/clinical_instructions.php
  modules/pdf_generator/report/communications.php
  modules/pdf_generator/report/demographics.php
  modules/pdf_generator/report/encounter.php
  modules/pdf_generator/report/history.php
  modules/pdf_generator/report/immunizations.php
  modules/pdf_generator/report/insurance.php
  modules/pdf_generator/report/issues.php
  modules/pdf_generator/report/patient_notes.php
  modules/pdf_generator/report/procedures.php
  modules/pdf_generator/report/soap.php
  modules/pdf_generator/report/speech_dictation.php
  modules/pdf_generator/report/transactions.php
  modules/pdf_generator/report/vitals.php
  modules/pdf_generator/selector.php
Labels: FEATURE: Printing/Export, Feature: Patient Demographics, Feature: Reports, GSoC2018, Re-Factoring

#1371 fix #1368: profile pictures on update user
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
Labels: enhancement

#1362 Style: Patient->Visits->Current->Clinical
  interface/forms/dictation/new.php
  interface/forms/reviewofs/new.php
  interface/forms/ros/templates/ros/general_new.php
  interface/forms/vitals/templates/vitals/general_new.php
Labels: GCI Task, UI: Refactor, UI: Style/Menu/Label

#1348 fix: button change to under form
  interface/patient_file/front_payment.php
Labels: GCI Task, UI: Style/Menu/Label

#1350 Fix: View facility styling
  interface/usergroup/assets/css/facility.css
  interface/usergroup/facility_user.php
  interface/usergroup/facility_user_admin.php
Labels: GCI Task, UI: Administration, UI: Style/Menu/Label

#1358 UI Fix: Clinical Instructions Form Styling
  interface/forms/clinical_instructions/new.php
Labels: Feature: Clinical Forms, GCI Task, UI: Refactor, UI: Style/Menu/Label

#1356 UI Fix: Load Lab Configuration Form Styling
  interface/orders/load_compendium.php
Labels: Feature: LABS, GCI Task, UI: Refactor, UI: Style/Menu/Label

#1303 Fix :FAB doesn't close when cursor moves away
  interface/main/tabs/main.php
Labels: GCI Task, UI: Layout

#1309 Fix #1308: Encounter Menu Content Blocking Dropdown
  interface/main/tabs/css/tabs.css
Labels: GCI Task, UI: Style/Menu/Label

#1304 Fix #1301: Calendar title no longer changes
  modules/calendar/search.php
Labels: Feature: Calendar, GCI Task

#1294 Fix #1292: Encounter Tabs Now Dropdown Upon Hover
  interface/patient_file/encounter/new_form.php
Labels: GCI Task, UI: Layout

#1318 Fix: Admin Title no longer obstructs nav
  interface/main/tabs/templates/user_data_template.php
Labels: GCI Task, UI: Style/Menu/Label

#1273 Fixed the sqlconf.php issue
  index.php
Labels: Feature: SETUP, GCI Task

#1297 Fix #1295: Add/Edit Profile Picture Button Not Well Displayed
  interface/patient_file/summary/demographics.php
Labels: GCI Task, UI: Style/Menu/Label
