Repository LibreHealthIO/lh-ehr, pull requests merged in 2019-03, with the labels that each got.

#1388 Update gitignore file
  .gitignore
Labels: House Keeping

#1366 style: added button styling in ACL
  interface/usergroup/adminacl.php
Labels: GCI Task, UI: Administration, UI: Refactor, UI: Style/Menu/Label

#1293 Fix #1291: Tab Value Colors Changed to Blue from White
  interface/themes/style_light.css
Labels: GCI Task, UI: Style/Menu/Label

#1424 Added changes to closed PR #1410
  interface/orders/orders_results.php
  interface/orders/types.php
Labels: House Keeping

#1339 Update menu.css
  interface/main/tabs/css/menu.css
Labels: UI: Style/Menu/Label

#1342 Fixes #1341 - Turned Button Texts to White
  interface/themes/style_light.css
  interface/themes/style_prism.css
Labels: GCI Task, UI: Style/Menu/Label

#1337 Fixing Unknown title for PDFs
  interface/patient_file/addr_label.php
  interface/patient_file/barcode_label.php
  interface/patient_file/label.php
Labels: FEATURE: Printing/Export, GCI Task

#1325 Fix: Broken links #1299
  interface/super/rules/controllers/alerts/view/list_actmgr.php
  interface/super/rules/controllers/browse/view/list.php
  interface/super/rules/controllers/browse/view/plans_config.php
  interface/super/rules/controllers/edit/view/action.php
Labels: GCI Task, UI: Style/Menu/Label
